### ISSUE TITLE
I can not show image

### ISSUE THREAD

**Issue by cool3690** [mudassar-tamboli/ESP32-OV7670-WebSocket-Camera#9]
hello,I use your code 
I have connect connected it
    `WiFi connected : IP address : 192.168.1.111  
    AP IP address: 192.168.4.1  
    WebSocket server started.  
    Http web server started.  
    `
but my camera does not show image...
it show
    `dhcps: send_nak>>udp_sendto result 0  
    dhcps: send_nak>>udp_sendto result 0  
 
    [0] Connected from 192.168.1.78 url: /  
    WStype a not handled   
    canvas_QQ_VGAdhcps: send_nak>>udp_sendto result 0  
    dhcps: send_nak>>udp_sendto result 0  
    `
my board is esp32+ov7670
but my ov7670 has a quiet different, I dont have XCLK  , PCLK I just have RCK
I dont know how can I do,please help me 
thanks

**Comment by luisvaag007** [comment]
Hi,  did you get it?

**Comment by cool3690** [comment]
I have sloved problem ,thanks.

**Comment by luisvaag007** [comment]
How did you did it?

**Comment by Oscilloscopy** [comment]
uhh
